name = "goose"
version = "0.1.0"
defaultTargets = ["Prelude", "Anoma", "Goose"]

[leanOptions]
relaxedAutoImplicit = false

[[lean_lib]]
name = "Goose"

[[lean_lib]]
name = "Anoma"

[[lean_lib]]
name = "Prelude"
