name = "goose"
version = "0.1.0"
defaultTargets = ["Prelude", "Anoma", "Goose", "Applib", "Apps"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.21.0"

[leanOptions]
relaxedAutoImplicit = false

[[lean_lib]]
name = "Goose"

[[lean_lib]]
name = "Anoma"

[[lean_lib]]
name = "Prelude"

[[lean_lib]]
name = "Applib"

[[lean_lib]]
name = "Apps"
