name = "goose"
version = "0.1.0"
defaultTargets = ["Prelude", "Anoma", "Goose", "Applib", "Apps"]

[leanOptions]
relaxedAutoImplicit = false

[[lean_lib]]
name = "Goose"

[[lean_lib]]
name = "Anoma"

[[lean_lib]]
name = "Prelude"

[[lean_lib]]
name = "Applib"

[[lean_lib]]
name = "Apps"
