name = "goose"
version = "0.1.0"
defaultTargets = ["Prelude", "Anoma", "AVM", "Applib", "Apps", "Goose", "Tests"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0"

[leanOptions]
relaxedAutoImplicit = false

[[lean_lib]]
name = "Prelude"

[[lean_lib]]
name = "Anoma"

[[lean_lib]]
name = "AVM"

[[lean_lib]]
name = "Applib"

[[lean_lib]]
name = "Apps"

[[lean_lib]]
name = "Goose"

[[lean_lib]]
name = "Tests"
